# Site settings

# Home page
index:
  en: 
  de: index-de.html
  hr: index-sr-hr-lat.html
  sr: index-sr-hr-cir.html

# Content
title:
  en: Memories and Recipes
  de: Erinnerungen und Rezepte
  hr: Sjećanja i recepte
  sr: Сећања и рецепти
flag:
  en: Memories and Recipes
  de: icon-flag-de.html
  hr: Sjećanja i recepte
  sr: Сећања и рецепти
description:
  en: This is a site that allows me to keep busy eating, writing and coding! It has me posting about food in a number of languages that I speak so that I don’t forget them, while learning about the software behind this page which is hosted for free. Hope you enjoy reading!
  de: Ein Blog über's Essen, auf drei Sprachen. Naja, vier, wenn man das vierte Alphabet auch zählt.
  hr: Moj blog o hrani, na tri jezikama. Pa dobro, četiri, ako računate dodatnu abecedu.
  sr: Мој блог о храни, на три језикама. Па добро, четири, ако рачунате додатну абецеду.
twitter_username: zojasav
github_username:  zojasavkovic

# URL config - deployed - base hostname and protocol for the site:
url: "http://zojasavkovic.github.io"

# Subpath of the site:
baseurl: "/memoriesandrecipes"

# Build settings
markdown: kramdown

# Google analytics:
google_analytics: UA-101663591-1
