# Site settings

# Home page
index:
  en: 
  de: index-de.html
  hr: index-hr.html
  sr: index-sr.html

# Content
title:
  en: Memories and Recipes
  de: Erinnerungen und Rezepte
  hr: Sjećanja i recepte
  sr: Сећања и рецепти
flag:
  en: icon-flag-en.html
  de: icon-flag-de.html
  hr: icon-flag-hr.html
  sr: icon-flag-sr.html
description:
  en: This is a blog that allows me to keep busy eating, writing and coding! It has me posting about food in a number of languages that I speak so that I don’t forget them, while learning about the software behind this site which is hosted for free. Hope you enjoy reading!
  de: Dies ist ein Blog, der mir erlaubt, beschäftigt zu essen, zu schreiben und zu codieren! Es hat mich über das Essen in einer Reihe von Sprachen, die ich spreche, damit ich sie nicht vergessen, während das Lernen über die Software hinter dieser Website, die kostenlos gehostet wird. Hoffe, dass Sie gerne lesen!
  hr: Moj blog o hrani, na tri jezikama. Pa dobro, četiri, ako računate dodatnu abecedu.
  sr: Мој блог о храни, на три језикама. Па добро, четири, ако рачунате додатну абецеду.
twitter_username: zojasav
github_username:  zojasavkovic
linkedin_username:  zojasavkovic

# URL config - deployed - base hostname and protocol for the site:
url: "http://zojasavkovic.github.io"

# Subpath of the site:
baseurl: "/memoriesandrecipes"

# Build settings
markdown: kramdown

# Google analytics:
google_analytics: UA-101663591-1
